name: yc-cd-prod
on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  Production-Deployment:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/env
          mode: prod
      - name: show env variables
        run: |
          echo "group: ${{ env.group }}"
          echo "workspace: ${{ env.workspace }}"
          echo "location: ${{ env.location }}"
          echo "compute: ${{ env.compute }}"  
          echo "endpoint: ${{ env.endpoint }}" 

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_YUENCHE }} #setup  replace AZURE_CREDENTIALS_JAMES with the name of your Azure credentials secret in GitHub

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y --version 2.2.1
          sudo apt install jq
          pip install yq
      
      - name: Run deployment to staging
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: ${{ env.group }}  #setup replace azureml with the name of your resource group in Azure
          workspaceName: ${{ env.workspace }} #setup replace ws01ent with the name of your workspace in Azure
          endpointName: ${{ env.endpoint }} 
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: src/workshop/core/scoring/deployment.yml
          modelVersion: latest
      
      - name: Test deployment to staging
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: ${{ env.group }}  #setup replace azureml with the name of your resource group in Azure
          workspaceName: ${{ env.workspace }} #setup replace ws01ent with the name of your workspace in Azure
          endpointName: ${{ env.endpoint }} 
          endpointFile: src/workshop/core/scoring/endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          resourceGroup: ${{ env.group }}  #setup replace azureml with the name of your resource group in Azure
          workspaceName: ${{ env.workspace }} #setup replace ws01ent with the name of your workspace in Azure
          endpointName: ${{ env.endpoint }} 
          endpointFile: src/workshop/core/scoring/endpoint.yml