name: yc-cd-staging
on:
  workflow_dispatch:
  workflow_run:
    workflows: [new-ci-train]
    types:
      - completed
  push:
    branches: 
      - integration
    paths:
      - .github/workflows/yc_scoring_unit_test.yml
      - .github/workflows/yc_cd_staging.yml

jobs:
  Staging-Deployment:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: src/workshop/env
          mode: staging
      - name: show env variables
        run: |
          echo "group: ${{ env.group }}"
          echo "workspace: ${{ env.workspace }}"
          echo "location: ${{ env.location }}"
          echo "compute: ${{ env.compute }}"  
          echo "endpoint: ${{ env.endpoint }}" 

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_YUENCHE }} #setup  replace AZURE_CREDENTIALS_JAMES with the name of your Azure credentials secret in GitHub

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y --version 2.2.1
          sudo apt install jq
          pip install yq
      
      - name: Run deployment to staging
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          resourceGroup: ${{ env.group }}  #setup replace azureml with the name of your resource group in Azure
          workspaceName: ${{ env.workspace }} #setup replace ws01ent with the name of your workspace in Azure
          endpointName: ${{ env.endpoint }} 
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: src/workshop/core/scoring/deployment.yml
          modelVersion: latest
      
      - name: Test deployment to staging
        uses: ./.github/actions/aml-endpoint-test
        with:
          resourceGroup: ${{ env.group }}  #setup replace azureml with the name of your resource group in Azure
          workspaceName: ${{ env.workspace }} #setup replace ws01ent with the name of your workspace in Azure
          endpointName: ${{ env.endpoint }} 
          endpointFile: src/workshop/core/scoring/endpoint.yml
          requestFile: src/workshop/core/scoring/scoring_test_request.json
  
  pull-request:
    if: ${{ success() }}
    needs: [Staging-Deployment]
    runs-on: ubuntu-latest
    steps:      
      - name: Create Pull Request to main
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.YUENCHE_GITHUB_SECRET }} #setup: provide your github secret name
          head: ${{ github.ref }}
          base: main
          title: "An automatically created PR by staging deployment completed to main"

